### ISSUE TITLE
Losing settings

### ISSUE THREAD

**Issue by doc1011** [realA10001986/Flux-Capacitor#1] opened 2023-12-18 19:13 UTC
Hi there

I'm running the latest code and have noticed twice now that flux capacitor will randomly lose its settings completely. It has happened randomly, where it is in screensaver mode (not active at all) and then crash with all settings lost and running continuously. It has an SD card and it had been set to save settings to the SD card - not sure if that could cause the issue? The card itself reads fine and there is no corruption.

The Flux Capacitor is linked wirelessly to a TCD, which is also running the latest version of your code. It's been working flawlessly. 

Any suggestions or troubleshooting? Thanks - and your code is awesome!

**Comment by realA10001986** [comment] 2023-12-18 20:05
Interesting. For how long did you have it run before it crashed (approx)?

The main settings are not saved to the SD card (only in flash memory), I don't think the SD card has anything to do with it. 

Are you compiling yourself or using the pre-compiled bin? Is your USB on the ESP32 accessible, ie can you connect the FC to a computer to follow the log?

**Comment by realA10001986** [comment] 2023-12-18 20:07
Also:

Did it do that with previous versions of the firmware, too?

When it reboots upon the crash, do the outer LEDs blink for a while before the startup sequence is played? (That would indicate that it reformats the flash file system and write a default settings file; I just have no idea why - even when the ESP32 does crash for whatever reason, the flash file system would be corrupt)

**Comment by doc1011** [comment] 2023-12-18 20:09
It was idle for a few hours I think each time it happened. It's happened once with the current firmware and once with the previous firmware. I've used the pre-compiled bin's each time. I can easily access the USB on the ESP32 so if there are logs etc happy to have a look of course.

**Comment by realA10001986** [comment] 2023-12-18 20:14
I probably never had it run that long; I will test this over the coming days, and if I can't reproduce it I will ask you for a log. To see the log, you need to install Arduino IDE on your computer and the SLAB CP210x driver (instructions for doing this are in the "fluxcapacitor-A10001986.ino" file)

**Comment by doc1011** [comment] 2023-12-18 20:17
Cheers mate. I've got Arduino IDE on my computer so let me know if you need anything.

**Comment by realA10001986** [comment] 2023-12-18 20:22
Do you use HomeAssistent, or is that disabled? What are yout settings under "Wireless Communications", especially the checkboxes?

**Comment by doc1011** [comment] 2023-12-18 20:31
Homeassistant is disabled on the FC but it's enabled on the TCD. Here's a screenshot below of the Wireless Communications settings (setup as they were before everything was reset). It may be a red herring but its possible the TCD's IP renewed to something different - could that be a cause? 

<img width="499" alt="Screenshot 2023-12-18 at 20 29 28" src="https://github.com/realA10001986/Flux-Capacitor/assets/42011383/cd4eca28-556c-4011-a99a-18dd3ded5576">

**Comment by realA10001986** [comment] 2023-12-18 21:07
It shouldn't be. BTTFN is UDP, if the packets are lost, they are lost, and apart from sending another one, nothing happens.

When you say "hours", are we talking 2-3 or closer to 10hrs?

**Comment by doc1011** [comment] 2023-12-18 21:09
Today when it happened it was around 3 or 4 hours.

**Comment by realA10001986** [comment] 2023-12-18 21:13
Any FC action before the screen saver came on, like time travels, IR remote commands, anything, or plain booting and waiting?

What I don't get is how the file system can get lost. There is no FS access when it just sits there and does nothing, and even if the ESP32 crashes for whatever reason, this should by no means affect the flash memory. I will have mine running during the night, but it would be helpful if you could hook up yours to your computer and see if you can get the log going (Arduino IDE: Tools -> Serial Monitor; provided you have the correct Port selected and the SLAB driver installed)

**Comment by doc1011** [comment] 2023-12-18 21:16
No, nothing. I had left it on and then noticed later the flux sound was running (I had set it to auto off after 30 secs). When I checked the settings they had all been reset. The only action I can think of is there is an hourly chime I setup recently on the TCD and it was 7 minutes past the hour when I noticed the issue with the FC. I'll have a go with setting up the logging.

**Comment by realA10001986** [comment] 2023-12-18 21:32
Last question for today: Any other BTTFN clients running, like eg SID?

**Comment by doc1011** [comment] 2023-12-18 21:33
:) Just the TCD and the FC

**Comment by realA10001986** [comment] 2023-12-19 06:20
Had mine running now for 8 hours (screen saver, delay 1 min), no issues. Left it on, fake-powered off (which is not much difference to the screen saver running), before going to work, will check tonight again.

Maybe this is a hardware problem, like overheating or a bad ESP32 dev board...? Is your FC complete with Stahlin box, or is the PCB "out in the air"? http://flux.local/info gives you, among other data, the chip temperature. Although this is sometimes (horribly) wrong, it might give a hint. On my TCD here in my office it shows 47 deg C.

**Comment by doc1011** [comment] 2023-12-19 18:18
Cheers mate. Mine's been running as well and it's not happened again yet. I've had th logging on and other than expected IR signals there's nothing else.

I've attached a pic of the esp32 info. Looks ok? It's not in the box yet so shouldn't be overheating.

![image](https://github.com/realA10001986/Flux-Capacitor/assets/42011383/a2028289-d505-4f50-8aac-70861a04b52e)

**Comment by realA10001986** [comment] 2023-12-19 18:54
Mine is at 48 deg C, after 17 hours - in the box. Why is yours so hot....? Is the temperature shown consistent on page reloads? (I have seen wrong temps here sometimes)

**Comment by realA10001986** [comment] 2023-12-19 18:58
OTOH, up to 85 deg is no problem, I googled. 

Anyway, I'd recommend observing more, leave it on with the log running, maybe it happens again.... I'll leave mine on over the night, too.

**Comment by doc1011** [comment] 2023-12-20 18:59
Temps look ok and are changing slightly so seems to be accurate. I've put the logs below but they seem fine I think.  It hasn't lost its settings again yet - uptime at 2713 mins and counting... 

21:45:41.293 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
21:45:41.293 -> mode:DIO, clock div:2
21:45:41.293 -> load:0x3fff0030,len:1344
21:45:41.293 -> load:0x40078000,len:13808
21:45:41.293 -> load:0x40080400,len:3608
21:45:41.293 -> entry 0x400805f0
21:45:41.293 -> ets Jul 29 2019 12:21:46
21:45:41.293 -> 
21:45:41.293 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
21:45:41.293 -> configsip: 0, SPets Jul 29 2019 12:21:46
21:45:41.293 -> 
21:45:41.293 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
21:45:41.293 -> configsip: 0, SPIWP:0xee
21:45:41.293 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
21:45:41.293 -> mode:DIO, clock div:2
21:45:41.293 -> load:0x3fff0030,len:1344
21:45:41.293 -> load:0x40078000,len:13808
21:45:41.527 -> load:0x40080400,len:3608
21:45:41.527 -> entry 0x400805f0
21:45:41.748 -> 
21:45:44.213 -> Flux Capacitor version V1.27 DEC092023
21:45:53.327 -> handleIRinput: Received IR code 0xd7e84b1b
21:45:59.330 -> handleIRinput: Received IR code 0xa3c8eddb
21:46:06.344 -> handleIRinput: Received IR code 0xd7e84b1b
22:59:38.233 -> handleIRinput: Received IR code 0x488f3cbb
22:59:42.610 -> handleIRinput: Received IR code 0x8c22657b
22:59:43.928 -> handleIRinput: Received IR code 0x8c22657b
22:59:44.889 -> handleIRinput: Received IR code 0x8c22657b
22:59:45.945 -> handleIRinput: Received IR code 0x449e79f
22:59:46.421 -> handleIRinput: Received IR code 0x449e79f
22:59:46.927 -> handleIRinput: Received IR code 0x449e79f
22:59:47.810 -> handleIRinput: Received IR code 0x1bc0157b
22:59:48.373 -> handleIRinput: Received IR code 0x1bc0157b
22:59:48.917 -> handleIRinput: Received IR code 0x1bc0157b
22:59:49.653 -> handleIRinput: Received IR code 0x1bc0157b
16:51:51.750 -> handleIRinput: Received IR code 0xd7e84b1b
16:51:54.105 -> handleIRinput: Received IR code 0xd7e84b1b
16:52:00.697 -> handleIRinput: Received IR code 0xd7e84b1b
19:03:36.607 -> handleIRinput: Received IR code 0x3d9ae3f7
19:03:38.349 -> handleIRinput: Received IR code 0x3d9ae3f7
19:03:41.904 -> handleIRinput: Received IR code 0x97483bfb

**Comment by realA10001986** [comment] 2023-12-20 20:05
Nothing here either, up since day before yesterday. I switched mine off now.

Where are the IR signals coming from? Did you use the FC's remote, or a different one, possibly controlling something else (those log entries are shown for every IR signal received)?

**Comment by realA10001986** [comment] 2023-12-28 21:36
Closing this for now, feel free to re-open if new info becomes available.

**Closed as completed by realA10001986** 2023-12-28 21:36 UTC
